backend:
  name: github
  repo: travispamaral/gatsby

media_folder: static/assets

collections:
  - name: project
    label: Project
    folder: project
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
